on:
  push:
    tags:
    - '*'

name: Publish Dev NPM package
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: build
        run: npm run test
      - name: Publish
        uses: menduz/oddish-action@master
        with:
          cwd: ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
